import { FC } from "react";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import "@/styles/globals.css";

import { auth } from "@/auth";

import { cn } from "@/lib/utils";
import { geistSans } from "@/lib/fonts";

import { Toaster } from "@/components/ui/sonner";

import QueryProvider from "@/components/providers/query-provider";

import { PropsWithChildren } from "@/types/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = async ({ children }) => {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn("font-geist-sans", geistSans.variable)}>
          <QueryProvider>
            {children}
            <Toaster />
          </QueryProvider>
        </body>
      </html>
    </SessionProvider>
  );
};

export default RootLayout;
