import { FC } from "react";
import type { Metadata } from "next";

import "@/styles/globals.css";

import { cn } from "@/lib/utils";
import { geistSans } from "@/lib/fonts";

import { PropsWithChildren } from "@/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn("font-geist-sans", geistSans.variable)}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
