import type { Metadata } from "next";
import { ReactNode } from "react";

import { cn } from "@/common/libs/cn";

import { gtSuper, sohne } from "@/common/styles/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={cn("", gtSuper.variable, sohne.variable)}>
        {children}
      </body>
    </html>
  );
}
