import type { Metadata } from "next";

import "@/styles/globals.css";

import { cn } from "@/lib/utils";
import { geistSans } from "@/lib/fonts";

import { PropsWithChildren } from "@/types/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={cn("font-geist", geistSans.variable)}>{children}</body>
    </html>
  );
}
